import logging, re
from typing import Dict
from io import BytesIO
logger = logging.getLogger(__name__)

SECTION_ORDER = ["title_block","complaint_body","prayer","list_of_witnesses","list_of_documents","affidavit","evidence_affidavit"]

def generate_pdf_bytes(case_id: str, case_type: str, sections: Dict) -> bytes:
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable, PageBreak
        from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_RIGHT
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2.5*cm, leftMargin=3*cm, topMargin=2.5*cm, bottomMargin=2.5*cm)
        def s(n, **kw): return ParagraphStyle(n, **kw)
        court_s  = s('C', fontName='Times-Bold',   fontSize=13, alignment=TA_CENTER, leading=20, spaceAfter=2)
        heading  = s('H', fontName='Times-Bold',   fontSize=12, alignment=TA_CENTER, leading=20, spaceBefore=10, spaceAfter=8)
        body     = s('B', fontName='Times-Roman',  fontSize=12, alignment=TA_JUSTIFY, leading=22, spaceAfter=8)
        right_s  = s('R', fontName='Times-Roman',  fontSize=12, alignment=TA_RIGHT, leading=20, spaceBefore=16)
        footer_s = s('F', fontName='Times-Roman',  fontSize=9, textColor=colors.grey, alignment=TA_CENTER, spaceBefore=20)
        def safe(t): return (t or "").replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')
        story = []
        first = True
        for key in SECTION_ORDER:
            content = sections.get(key, "")
            if not content: continue
            if not first: story.append(PageBreak())
            first = False
            for line in content.split('\n'):
                ls = line.strip()
                if not ls: story.append(Spacer(1, 6)); continue
                if ls.isupper() and len(ls) < 100:
                    story.append(Paragraph(safe(ls), court_s if key=="title_block" else heading))
                elif ls in ('Deponent','COMPLAINANT','Counsel') or ls.startswith('Dated') or ls.startswith('Through'):
                    story.append(Paragraph(safe(ls), right_s))
                elif re.match(r'^\d+\.', ls):
                    story.append(Paragraph(safe(ls), body))
                else:
                    story.append(Paragraph(safe(ls), body))
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey, spaceBefore=30))
        story.append(Paragraph(f"Generated by LegalDraftAI &nbsp;|&nbsp; Case: {case_id[:8]} &nbsp;|&nbsp; {case_type} &nbsp;|&nbsp; Academic use only", footer_s))
        doc.build(story)
        return buffer.getvalue()
    except Exception as e:
        logger.error(f"PDF failed: {e}")
        return _html(case_id, case_type, sections).encode("utf-8")

def _html(case_id, case_type, sections):
    body = ""
    for k in SECTION_ORDER:
        c = sections.get(k,"")
        if c:
            sc = c.replace('&','&amp;').replace('<','&lt;').replace('>','&gt;')
            body += f'<div class="pg"><pre>{sc}</pre></div>\n'
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><style>
body{{font-family:"Times New Roman",serif;font-size:12pt;line-height:2;color:#000;background:#fff}}
.pg{{padding:2.5cm 3cm;page-break-after:always;min-height:100vh}}
pre{{font-family:inherit;white-space:pre-wrap;text-align:justify}}
.ft{{font-size:9pt;color:#888;border-top:1px solid #ccc;padding:10px 3cm;text-align:center}}
@media print{{.pg{{page-break-after:always}}}}
</style></head><body>{body}
<div class="ft">LegalDraftAI | Case: {case_id[:8]} | {case_type} | Academic use only</div>
</body></html>"""
